### ISSUE TITLE
angularjs noassign error

### ISSUE THREAD

**Issue by mason105** [gaug-cns/ros-control-center#1]
at  topic_views/default.html 
<input type="text" class="form-control" ng-model="$parent.latest_message | json : 0" ng-readonly="$parent.is_subscribing" placeholder="JSON"> 

“| json : 0” cause ngModel:nonassin Non-Assignable Expression error at chrome console.
I delete this ,it's seems ok, am i right?

**Comment by pantor** [comment]
You're right, thanks for pointing out.
