### ISSUE TITLE
call_service ServiceException

### ISSUE THREAD

**Issue by sonyccd** [gaug-cns/ros-control-center#13]
`[ERROR] [WallTime: 1457295012.672246] [Client 0] [id: call_service:/rosapi/service_type:32] call_service ServiceException: service [/rosapi/service_type] responded with an error: error processing request: field type must be of type str`

I am running indigo, have used rosbidge_websocket before with no problem.

**Comment by marcoarruda** [comment]
I had this problem, but I was trying to use roslibjs, not ros-control-center, but I believe that it's the same situation.
To resolve it I had uninstalled rosbridge_suite package then cloned the repository (current development source code) and compiled. I had also to install ros-auth, then it is just launch rosbridge server.

I hope I've helped.
