### ISSUE TITLE
start with ros-control-center

### ISSUE THREAD

**Issue by vkuehn** [gaug-cns/ros-control-center#18]
it was easy to find where the messages are defined but I struggle to find anything else e.g. the joystick tab view. I would like to look at it but I am new to angular, can you kindly point to it ? or provide a mail adress to chat about that ?

Thanks

**Comment by shoemakerlevy9** [comment]
Looks like the Joystick tab view is defined in the /app/topics/sensor_msgs/Joy.html file

**Comment by pantor** [comment]
I added my mail address to my profile, so feel free to contact me. Sorry for the delay...
