### ISSUE TITLE
README Installation instructions do not function

### ISSUE THREAD

**Issue by c-andy-martin** [gaug-cns/ros-control-center#20]
I attempted to follow this part of the instructions on the README:

Open the ROS Control Center at https://pantor.github.io/ros-control-center. In the settings tab, you need to enter the IP address and port of your robot. Open the Control tab and reload.

I type in the settings to reach my rosbridge_server (address "localhost", port "9090"). When I click 'control' it just clears the form. If I reload the page, it just clears the form. I see no way to submit the settings to be stored (there is no "submit" button). I have tried "localhost", "127.0.0.1", etc. to no avail. I have tried both firefox and chrome, same symptoms.

**Comment by ceesietopc** [comment]
I have the same problem. When running somewhat older commit 705b025 locally, the problem does not exist. The error has something to do with the default settings:
`angular.min.js:107 TypeError: Settings.getDefaultSetting is not a function`


Probably has something to do with this change. [https://github.com/pantor/ros-control-center/commit/8cd1e1fea29e7ab00ab61780ea0561d492519503#diff-c9b527a2440917e1fbde1514e0b73d52L51](https://github.com/pantor/ros-control-center/commit/8cd1e1fea29e7ab00ab61780ea0561d492519503#diff-c9b527a2440917e1fbde1514e0b73d52L51)

**Comment by yonhdee** [comment]
i am in the same no-response situation, gulp with these logs:
/var/www/ros-control-center/app/control/control.controller.js
   41:47  warning  Unexpected block statement surrounding arrow body       arrow-body-style
  113:7   warning  Assignment to property of function parameter 'message'  no-param-reassign
  117:7   warning  Assignment to property of function parameter 'message'  no-param-reassign

/var/www/ros-control-center/app/helper/domains.service.js
  29:9  warning  Assignment to property of function parameter 'entry'  no-param-reassign
  45:9  warning  Assignment to property of function parameter 'entry'  no-param-reassign

✖ 5 problems (0 errors, 5 warnings)

**Comment by pantor** [comment]
Does this issue still exist with the latest commit?

**Comment by DanMcGann** [comment]
Yes the same issues are still prevalent as of now (May 26 2017).
The settings tab cannot accept saving new settings, and the control tab seems to be broken, or unreachable as the button in the upper right corner re directs you to the broken settings page.

**Comment by pantor** [comment]
@DanMcGann Can you give me some information about the browser / OS / Ros Version? Are there any errors in the console output of the browser?
