### ISSUE TITLE
Abandoned project?

### ISSUE THREAD

**Issue by agjunyent** [gaug-cns/ros-control-center#21]
Almost 6 months since last push, and a lot of comments saying this does not work.

I have the same errors of the opened issues.

Is this project abandoned?

**Comment by vkuehn** [comment]
it can't work as there is no final version of the communication protocol for ardumower. Once that is finished I will instantly continue on it...if there something which could be of course you can mention that any time

**Comment by pantor** [comment]
I've published some bug fixes and improvements in the last days. While I'm not sure whether I resolved all opened issues, maybe you can give it a try and send me some more information if it's still not working. Thanks!

**Comment by agjunyent** [comment]
Oh! 
Thanks a lot pantor! I'll try these days again everything and report if I find any bug, or if I can solve any other oppened issue.

Thanks again!
