### ISSUE TITLE
how to run ros-control-center in Local machine manually..?

### ISSUE THREAD

**Issue by nageshpindi** [gaug-cns/ros-control-center#26]
Hi guys,
i'm using ros-control-center with logistics Application it's working fine. But manually i'm not able to access the ros-control-center so can one of you explain how to start manually. And below is the error i'm getting.
The serve command requires to be run in an Angular project, but a project definition could not be found.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ros-control-center@0.8.0 start: `ng serve --base-href=`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ros-control-center@0.8.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rosplan/.npm/_logs/2019-01-07T11_17_10_064Z-debug.log

Thanks in advance.

**Comment by johnflux** [comment]
Run:

npm install
