### ISSUE TITLE
does it works locally...?

### ISSUE THREAD

**Issue by nageshpindi** [gaug-cns/ros-control-center#28]
The ROS Control Center works from the browser, so it should connect easily in principle.

Are there any errors in the console output?
doesn't it works without browser....? It is working fine with browser. But its not working locally. I need clarification for that. Can u give me reply as soon as possible.

**Comment by johnflux** [comment]
https:// to ws:// is disallowed by default on firefox.

Go to firefox's about:config and toggling network.websocket.allowInsecureFromHTTPS to true

https://stackoverflow.com/questions/11768221/firefox-websocket-security-issue/12042843#12042843
