### ISSUE TITLE
Doesn't seem to work with robot on local network

### ISSUE THREAD

**Issue by nickvaras** [gaug-cns/ros-control-center#30]
Even when trying the demo page, I can see topics if running a local rosbridge server on same machine (127.0.0.1), but not a robot in the local network, for example 10.66.171.50. The dashboard banner goes green but gets stuck in "Loading" with no further information.

**Comment by nickvaras** [comment]
Correction to the above. It seems to work only when running a simple server on my laptop, but when I plugged a monitor to the robot (so the ws server lived on 127.0.0.1:9090) and tried to open the web demo, I got the same result, i.e., got stuck in the "loading..." bubble.

**Comment by johnflux** [comment]
https:// to ws:// is disallowed by default on firefox.

Go to firefox's about:config and toggling network.websocket.allowInsecureFromHTTPS to true

https://stackoverflow.com/questions/11768221/firefox-websocket-security-issue/12042843#12042843

**Comment by nickovaras** [comment]
Thanks!

**Comment by nickvaras** [comment]
Thanks!
