### ISSUE TITLE
localStorageService.get('settings') will be null at first time

### ISSUE THREAD

**Issue by mason105** [gaug-cns/ros-control-center#4]
As the title shows,when someone first time run this , localStorageService.get('settings') shows null.
This cause line8 at  root.controller.js  through a exception, js just terminal here.
May be need add some check.

**Comment by mason105** [comment]
Also I want add some function to this project.May I?
The first thing  I want to add is ROS_LOG view windows.In this way, can quickly take a look of log stream without ssh or other tools.Also add a log level setting will be great.

**Comment by pantor** [comment]
The issue should be fixed with the latest commit. 

Of course, any help is always appreciated! The project is more-or-less a side project and still in it's early stages, but if you have a feature idea or request, you can either open a new issue or make a pull request.
