### ISSUE TITLE
Without Node

### ISSUE THREAD

**Issue by mason105** [gaug-cns/ros-control-center#8]
some topic  has a this without node tag.what does this mean?
![ye3bie 2sgrqbk3zvvkmbzj](https://cloud.githubusercontent.com/assets/2382441/11945469/11cf1e0e-a88b-11e5-85ea-f8f00a182563.png)

**Comment by pantor** [comment]
The _Without Node_ label was just a reminder for me. Since it only works with a specific naming convention, I'll remove it soon.
